C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100
C:\xampp\php\php.exe C:\Lcg\cytek\biolegend\calculate-delta.php 100