C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 500
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 300
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100
C:\xampp\php\php.exe C:\Lcg\webscrape\store-delta.php 100